export const statesSwitch = (state) => {
  switch(state) {
    case 'US-AL':
      return 1
    case 'US-AK':
      return 2
    case 'US-AZ':
      return 3
    case 'US-AR': 
      return 4
    case 'US-CA':
      return 5
    case 'US-CO':
      return 6
    case 'US-CT':
      return 7
    case 'US-DE':
      return 8
    case 'US-FL':
      return 9
    case 'US-GA':
      return 10
    case 'US-HI':
      return 11
    case 'US-ID':
      return 12
    case 'US-IL':
      return 13
    case 'US-IN':
      return 14
    case 'US-IA':
      return 15
    case 'US-KS':
      return 16
    case 'US-KY':
      return 17
    case 'US-LA':
      return 18
    case 'US-ME':
      return 19
    case 'US-MD':
      return 20
    case 'US-MA':
      return 21
    case 'US-MI':
      return 22
    case 'US-MN':
      return 23
    case 'US-MS':
      return 24
    case 'US-MO':
      return 25
    case 'US-MT':
      return 26
    case 'US-NE':
      return 27
    case 'US-NV':
      return 28
    case 'US-NH':
      return 29
    case 'US-NJ':
      return 30
    case 'US-NM':
      return 31
    case 'US-NY':
      return 32
    case 'US-NC':
      return 33
    case 'US-ND':
      return 34
    case 'US-OH':
      return 35
    case 'US-OK':
      return 36
    case 'US-OR':
      return 37
    case 'US-PA':
      return 38
    case 'US-RI':
      return 39
    case 'US-SC':
      return 40
    case 'US-SD':
      return 41
    case 'US-TN':
      return 42
    case 'US-TX':
      return 43
    case 'US-UT':
      return 44
    case 'US-VT':
      return 45
    case 'US-VA':
      return 46
    case 'US-WA':
      return 47
    case 'US-WV':
      return 48
    case 'US-WI':
      return 49
    case 'US-WY':
      return 50
  }
}